[project]
name = "hpdex"
version = "0.1.2"
description = "High-Performance Parallel Differential Expression Analysis for Single-Cell Data"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=1.23.5",
    "scipy>=1.11.0",
    "numba>=0.58.0",
    "pandas>=1.5.0",
    "anndata>=0.8.0",
    "tqdm>=4.64.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/hpdex"]

[dependency-groups]
test = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "numpy>=1.23.5",
    "scipy>=1.11.0",
    "pandas>=1.5.0",
    "anndata>=0.8.0",
    "scanpy>=1.9.0",
]