if(EXISTS "/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/bench_sort[1]_tests.cmake")
  include("/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/bench_sort[1]_tests.cmake")
else()
  add_test(bench_sort_NOT_BUILT bench_sort_NOT_BUILT)
endif()
