if(EXISTS "/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/bit_pack_test[1]_tests.cmake")
  include("/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/bit_pack_test[1]_tests.cmake")
else()
  add_test(bit_pack_test_NOT_BUILT bit_pack_test_NOT_BUILT)
endif()
