if(EXISTS "/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/blockwise_combine_test[1]_tests.cmake")
  include("/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/blockwise_combine_test[1]_tests.cmake")
else()
  add_test(blockwise_combine_test_NOT_BUILT blockwise_combine_test_NOT_BUILT)
endif()
