if(EXISTS "/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/concat_test[1]_tests.cmake")
  include("/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/concat_test[1]_tests.cmake")
else()
  add_test(concat_test_NOT_BUILT concat_test_NOT_BUILT)
endif()
