if(EXISTS "/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/foreach_vec_test[1]_tests.cmake")
  include("/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/foreach_vec_test[1]_tests.cmake")
else()
  add_test(foreach_vec_test_NOT_BUILT foreach_vec_test_NOT_BUILT)
endif()
