if(EXISTS "/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/highway_test[1]_tests.cmake")
  include("/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/highway_test[1]_tests.cmake")
else()
  add_test(highway_test_NOT_BUILT highway_test_NOT_BUILT)
endif()
