if(EXISTS "/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/masked_minmax_test[1]_tests.cmake")
  include("/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/masked_minmax_test[1]_tests.cmake")
else()
  add_test(masked_minmax_test_NOT_BUILT masked_minmax_test_NOT_BUILT)
endif()
