if(EXISTS "/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/mask_slide_test[1]_tests.cmake")
  include("/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/mask_slide_test[1]_tests.cmake")
else()
  add_test(mask_slide_test_NOT_BUILT mask_slide_test_NOT_BUILT)
endif()
