if(EXISTS "/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/minmax_magnitude_test[1]_tests.cmake")
  include("/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/minmax_magnitude_test[1]_tests.cmake")
else()
  add_test(minmax_magnitude_test_NOT_BUILT minmax_magnitude_test_NOT_BUILT)
endif()
