if(EXISTS "/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/minmax128_test[1]_tests.cmake")
  include("/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/minmax128_test[1]_tests.cmake")
else()
  add_test(minmax128_test_NOT_BUILT minmax128_test_NOT_BUILT)
endif()
