if(EXISTS "/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/mul_by_pow2_test[1]_tests.cmake")
  include("/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/mul_by_pow2_test[1]_tests.cmake")
else()
  add_test(mul_by_pow2_test_NOT_BUILT mul_by_pow2_test_NOT_BUILT)
endif()
