if(EXISTS "/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/mul_pairwise_test[1]_tests.cmake")
  include("/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/mul_pairwise_test[1]_tests.cmake")
else()
  add_test(mul_pairwise_test_NOT_BUILT mul_pairwise_test_NOT_BUILT)
endif()
