if(EXISTS "/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/perf_counters_test[1]_tests.cmake")
  include("/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/perf_counters_test[1]_tests.cmake")
else()
  add_test(perf_counters_test_NOT_BUILT perf_counters_test_NOT_BUILT)
endif()
