if(EXISTS "/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/shuffle4_test[1]_tests.cmake")
  include("/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/shuffle4_test[1]_tests.cmake")
else()
  add_test(shuffle4_test_NOT_BUILT shuffle4_test_NOT_BUILT)
endif()
