if(EXISTS "/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/test_util_test[1]_tests.cmake")
  include("/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/test_util_test[1]_tests.cmake")
else()
  add_test(test_util_test_NOT_BUILT test_util_test_NOT_BUILT)
endif()
