if(EXISTS "/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/topology_test[1]_tests.cmake")
  include("/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/topology_test[1]_tests.cmake")
else()
  add_test(topology_test_NOT_BUILT topology_test_NOT_BUILT)
endif()
