if(EXISTS "/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/widen_mul_test[1]_tests.cmake")
  include("/Users/wzq/Documents/Code/Project/westlake/hpdex/build_test_cpp/highway_build/widen_mul_test[1]_tests.cmake")
else()
  add_test(widen_mul_test_NOT_BUILT widen_mul_test_NOT_BUILT)
endif()
