name: Build wheels

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true   # 拉取子模块（highway 等）

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"   # host 环境 Python，仅用于运行 cibuildwheel

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: cibuildwheel --output-dir dist
        env:
          CIBW_BUILD_VERBOSITY: 1   # 输出详细日志
          CIBW_SKIP: "pp*"          # 跳过 PyPy
          CIBW_TEST_COMMAND: ""     # 禁用测试

      - name: Upload wheels as artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: dist/*
